### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by Cesar5156** [Hydraxous/EasyPZ-ULTRAKILL#11]
Anytime i have p mode on and time drops from S to A, ezpz wont restart me.

**Comment by Hydraxous** [comment]
I understand you have p mode on, but for sake of being thorough will you please double check in the settings that EasyPZ/Auto Restart/Enable Auto Restart is in fact enabled.

Otherwise can you verify that in the settings, EasyPZ/Auto Restart/Only AutoRestart At Level End is disabled?
This setting would prevent auto-restart during a level if it's enabled, even if auto-restarts are enabled.

If that isn't the issue, can you please supply some more details such as
- version of EasyPZ
- version of Configgy
- any relevant screenshots
- level in which the issue occured
- BepInEx log if you have it

**Comment by Cesar5156** [comment]
i checked the settings, and cant really find the auto restart option? this could be because im searching the cfg, but cant find anything ingame related to easyPZ, but i do have a log:

[Message:   BepInEx] BepInEx 5.4.22.0 - ULTRAKILL (12/29/2023 10:54:10 AM)
[Info   :   BepInEx] Running under Unity v2019.4.40.16762411
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 5 plugins to load
[Info   :   BepInEx] Loading [PluginConfigurator 1.8.2]
[Info   :PluginConfigurator] Working path: C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\PluginConfigurator\PluginConfigurator.dll, Working dir: C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\PluginConfigurator
[Info   :PluginConfigurator] Dirty config detected. Saving configuration for Plugin Configurator : com.eternalUnion.pluginConfigurator
[Info   :PluginConfigurator] Saving to C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\config\PluginConfigurator\com.eternalUnion.pluginConfigurator.config
[Info   :PluginConfigurator] Plugin com.eternalUnion.pluginConfigurator is loaded!
[Info   :   BepInEx] Loading [Ultra Pain 1.1.0]
[Info   :Ultra Pain] Working path: C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\UltraPain\Ultrapain.dll, Working dir: C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\plugins\UltraPain
[Info   :Ultra Pain] Plugin Ultrapain is loaded!
[Info   :PluginConfigurator] Loaded sprite from https://c4.wallpaperflare.com/wallpaper/981/954/357/ultrakill-red-background-v1-ultrakill-weapon-hd-wallpaper-thumb.jpg successfully
[Info   :PluginConfigurator] Dirty config detected. Saving configuration for ULTRAPAIN : com.eternalUnion.ultraPain
[Info   :PluginConfigurator] Saving to C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\config\PluginConfigurator\com.eternalUnion.ultraPain.config
[Info   :   BepInEx] Loading [StyleEditor 1.0.2]
[Info   :StyleEditor] Plugin eternalUnion.ultrakill.styleEditor is loaded!
[Info   :   BepInEx] Loading [EasyPZ 2.0.2]
[Info   :    EasyPZ] EasyPZ Loaded. Good luck on P-ing in all the levels! :D
[Info   :   BepInEx] Loading [RcHud 1.2.1]
[Message:   BepInEx] Chainloader startup complete
[Info   :     RcHud] hud initialized
[Info   :PluginConfigurator] Dirty config detected. Saving configuration for Division : divisionTest
[Info   :PluginConfigurator] Saving to C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\config\PluginConfigurator\divisionTest.config
[Info   :PluginConfigurator] Dirty config detected. Saving configuration for Style Editor : eternalUnion.ultrakill.styleEditor
[Info   :PluginConfigurator] Saving to C:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\BepInEx\config\PluginConfigurator\eternalUnion.ultrakill.styleEditor.config

**Comment by Hydraxous** [comment]
I see, thanks for posting the log. The version of EasyPZ that you have is an older one. This issue should be fixed in the latest release. Please note the newer version requires Configgy, available at https://GitHub.com/Hydraxous/Configgy/releases/latest
