### ISSUE TITLE
Any% Goals

### ISSUE THREAD

**Issue by UntotenTheo** [Hydraxous/EasyPZ-ULTRAKILL#15]
**Is your feature request related to a problem? Please describe.**
i dont wanna have to manually set a custom goal every time i just want to beat someone elses/my own any% time

**Describe the solution you'd like**
Add any% options for Goal Modes
Example:
**Goal Mode:**
- LevelPRank
- Custom
- PersonalBestTimePRank
- HighestFriendTimePRank
- NextHighestFriendTimePRank
- PersonalBestTimeAny%
- HighestFriendTimeAny%
- NextHighestFriendTimeAny%

In case this is too cluttered (Which it probably is)
You can also just make a grayed out button be interactible if PB, HighestFriend or NextHighestFriend are selected, allowing you to choose either the P-Rank category or the Any% category.
Example:
**Goal Mode:**
- ~~LevelPrank~~
- ~~Custom~~
- PersonalBestTime
- HighestFriendTime
- NextHighestFriendTime

**Category:**
- Any%
- P-Rank

**Additional context**
nothing else to add

**Comment by Hydraxous** [comment]
I'm not quite sure I understand. What you're describing sounds like an existing feature when using ```Goal Mode``` in combination with ```Use P-Rank Stats for Goal``` option. Unchecking the Use P-Rank option and setting the goal mode to the desired one, it should use the any% times for the corresponding goal mode. If the goals are not properly being shown, it could also be an issue with EasyPZ or network.

**Comment by UntotenTheo** [comment]
it appears im a lil stupid my bad
closing issue
