### ISSUE TITLE
Menu doesn't work.

### ISSUE THREAD

**Issue by IWannaModGames** [Hydraxous/EasyPZ-ULTRAKILL#17]
**Describe The Bug**
Self explanitory, i press P and the menu doesnt pop up.

**Screenshots**
I think i cant screenshot anything

**LOG FILE IS LINKED TO THE REPORT!**
[LogOutput.log](https://github.com/Hydraxous/EasyPZ-ULTRAKILL/files/14470279/LogOutput.log)

**Comment by Hydraxous** [comment]
This isn't an intended feature. If you're looking for the configuration menu, you can access it by going to the pause menu and clicking the Configgy button next to options, then selecting EasyPZ from the root menu.

From the log you've provided... I notice that you are running the game with UMM. Please note that UMM is deprecated and no longer works in modern UK versions.

EasyPZ will need to be placed in ULTRAKILL/BepInEx/plugins/ along with it's dependency mod Configgy, which you can get [here](https://github.com/hydraxous/Configgy/releases/latest).

**Comment by IWannaModGames** [comment]
Thank you so much! **This works now!**
