### ISSUE TITLE
Cybergrind with EasyPZ seems to restart randomly

### ISSUE THREAD

**Issue by UltrioG** [Hydraxous/EasyPZ-ULTRAKILL#6]
Reproduction:
Step 1. Have EasyPZ
Step 2. Go to Cybergrind
Step 2.5? Turn **_on_** P-Mode
Step 3. Play Cybergrind
Step 4. Die

The score menu should not show up, instead V1 simply respawns.

Further testing may be requested.

**Comment by Hydraxous** [comment]
This should be resolved as of 3.0.0
